{-
# Positive Binary Numbers: Binary Operations
-}
module Numbers.Positive.OperationsBinary where

import Prelude hiding ( succ, pred )
import Numbers.Positive.Structure ( Positive (..) )
import Numbers.Positive.OperationsUnary ( succ, pred )

{-
## Addition of Two `Positive`

Standard inductive definition:
-}
add :: Positive -> Positive -> Positive
add XH     XH     = XO XH                -- 1 + 1       == 2
add XH     (XO n) = XI n                 -- 1 + 2n      == 2n+1
add XH     (XI n) = XO (succ n)          -- 1 + 2n+1    == 2(n + 1)
add (XO m) XH     = succ (XO m)          -- 2m + 1      == 2m+1
add (XI m) XH     = XO (succ m)          -- 2m+1 +    1 == 2m + 2 == 2(m + 1)
add (XO m) (XO n) = XO (add m n)         -- 2m   + 2n   == 2(m + n)
add (XO m) (XI n) = succ (XO (add m n))  -- 2m   + 2n+1 == 2(m + n) + 1
add (XI m) (XI n) = XO (succ (add m n))  -- 2m+1 + 2n+1 == (2m + 2n)+2 == 2((m + n)+1)
add (XI m) (XO n) = succ (XO (add m n))  -- 2m+1 + 2n   == 2(m + n)+1

{-
## Multiplication of Two `Positive`

The first version proceeds by induction on the first argument only:
-}
mul :: Positive -> Positive -> Positive
mul XH     y = y                    --   1 * y    == y
mul (XO b) y =        XO (mul b y)  --   2b   * y == 2(b * y)
mul (XI b) y = add y (XO (mul b y)) -- (2b+1) * y == (2b+1) * y
                                    --            == (2b * y) + y
                                    --            == 2(b * y) + y

{-
The second version proceeds by induction on both arguments, distinguishing the four cases generated by combinations of the first argument (even/odd) with the second (even/odd):
-}
mulAlt :: Positive -> Positive -> Positive
mulAlt XH y = y                             --         1 * y   == y
mulAlt y XH = y                             --         y * 1   == y
mulAlt (XO m) (XO n) = XO (XO (mulAlt m n)) --         2m * 2n == 2(2(m * n))
mulAlt (XO m) (XI n) = XO (add (XO (mulAlt m n)) m)            
                                            --     2m * (2n+1) == 2m * (2n+1)
                                            --                 == 2((m * 2n) + m)
                                            --                 == 2(2(m * n) + m)  
mulAlt (XI m) (XO n) = XO (add (XO (mulAlt m n)) n)            
                                            --     (2m+1) * 2n == (2m+1) * 2n
                                            --                 == 2(2m+1) * n)
                                            --                 == 2(2m * n + n)
                                            --                 == 2(2(m * n) + n)
mulAlt (XI m) (XI n) = succ (add (XO (mulAlt m n)) (add m n))  
                                            -- (2m+1) * (2n+1) == (2m+1) * 2n + (2m+1)
                                            --                 == (2m * 2n + 2n) + (2m+1)
                                            --                 == (2m * 2n) + 2(n + m) + 1
                                            --                 == 4(m * n) + 2(n + m) + 1
                                            --                 == 2(2(m * n) + (n + m)) + 1

{-
## Subtraction of Two `Positive`

Eventually, we want to define a Binary Numerical system on the datatype `BN`, defined in `Numbers.Binary.Functor.Structure` as `BN = BinNotation Positive`, once shown that `BinNotation a` is a functor.

Among the operations of a numerical system there is the subtraction. 

We will define a subtraction `sub:: BN -> BN -> BN` based on a subtraction acting on `Positive` values which cannot always yield elements of `Positive`. 

That is why we are going to define `sub :: Positive -> Positive -> Mask` where `Mask` is:
-} 
data Mask where
  IsNeg :: Mask -- denotes a negative value that cannot be in `Positive`
  IsNul :: Mask -- denotes zero that cannot be in `Positive`
  IsPos :: Positive -> Mask
  deriving (Show, Eq)

{-

To distinguish between two cases, the type of subtraction `sub` between two `Positive` values is:

~~~haskell
sub :: Positive -> Positive -> Mask
~~~

1. `IsNul` is the result to obtain from `sub` whenever the first argument is identical to the second one;
2. `IsNeg` is the result to obtain from `sub` whenever the first argument is strictly less than the second one;
3. `IsPos` is the result to obtain in every other case.

### Definition of `sub`

The function `sub` proceeds by induction on both arguments, distinguishing the four cases generated by combinations of the first argument (even/odd) with the second (even/odd).

When the difference between the first and second argument is strictly positive, the value of the difference is returned explicitly labeled as positive.
-}
sub :: Positive -> Positive -> Mask
sub XH     XH      = IsNul          -- 1 - 1 == "0"
sub XH     _       = IsNeg          -- 1 - n == "< 0"
sub m     XH       = IsPos (pred m) -- m - 1 == m-1
sub (XO m) (XO n) = 
  case sub m n of -- 2m - 2n == 2(m - n):
  IsNeg -> IsNeg          -- if m - n <  0...
  IsNul -> IsNul          -- if m - n == 0...
  IsPos s -> IsPos (XO s) -- if m - n >  0...

sub (XI m) (XO n) = 
  case sub m n of -- (2m+1) - 2n == 2m-2n+1 == 2(m - n)+1:
  IsNeg -> IsNeg                 -- if m - n <  0...
  IsNul -> IsPos XH              -- if m - n == 0...
  IsPos s -> IsPos (succ (XO s)) -- if m - n >  0...

sub (XO m) (XI n) = 
  case sub m n of -- (2m) - (2n+1) == (m+m)-(n+n+1)
                  --               == (m - n)+(m - n)-1
                  --               == 2(m - n)-1
  IsNeg -> IsNeg                 -- se m - n <  0...
  IsNul -> IsNeg                 -- se m - n == 0...
  IsPos s -> IsPos (pred (XO s)) -- se m - n >  0...

sub (XI m) (XI n) = 
  case sub m n of -- (2m+1) - (2n+1) == 2m-2n+1-1 
                  --                 == 2(m - n) 
  IsNeg -> IsNeg          -- if m - n <  0...
  IsNul -> IsNul          -- if m - n == 0...
  IsPos s -> IsPos (XO s) -- if m - n >  0...