SIM_DURATION 10
N_NANO_SECS 10000000
NOF_USERS 50
P_SERV_MIN 0.1
P_SERV_MAX 0.9
NOF_WORKER 8
NOF_WORKER_SEATS 4 
NOF_PAUSE 3
SERVICE_1 10
SERVICE_2 8
SERVICE_3 6
SERVICE_4 8
SERVICE_5 20
SERVICE_6 20
EXPLODE_THRESHOLD 25
N_REQUESTS 4
N_NEW_USERS 5