/****************************************** 
Lecture 2 - Floyd-Hoare Logic

    - Assignment
    - Consequence
    - Composition
    - Conditional

******************************************/

// Floyd forward method:

method MyMethod(x: int) returns (y: int)
    requires 10 <= x // 0
    ensures  25 <= y // 5
{
    assert 10 <= x; // 1
    var a := x + 3; 
    assert 10 <= x && a == x + 3; // 2
    var b := 12;
    assert 10 <= x && a == x + 3 && b == 12; // 3
    y := a + b;
    assert 10 <= x && a == x + 3 && b == 12 && y == a + b; // 4
    assert 10 <= x && a == x + 3 && b == 12 && y == a + b ==> 25 <= y; // 4 ==> 5
    assert 25 <= y; // 5
}

// Dijkstra backword method:

method MyMethod'(x: int) returns (y: int)
    requires 10 <= x // 1
    ensures  25 <= y // 2
{
    assert 10 <= x ==> 25 <= x + 3 + 12; // 1 ==> 5
    assert 25 <= x + 3 + 12; // 5
    var a := x + 3;
    assert 25 <= a + 12; // 4
    var b := 12;
    assert 25 <= a + b; // 3
    y := a + b;
    assert 25 <= y; // 2
}

/*  Hoare triples

    Remember that a state is a (partial) function from program variables to values;
    formally we set

              s : State = Var --> Val

    Let S be a program statement and s, t : State; then define the predicate 
   
              (S, s)=> t if the execution of S starting with s normally terminates with t

    Let P and Q be assertions, namely predicates of the states 
   
              P, Q : State --> Bool
   
    and let S be a program statement. Then we call {P} S {Q} a "Hoare-triple" and say that
    it is "valid" if

        forall s, t : State :: P s && (S, s)=> t ==> Q s

    Notice that if (S, s)=> t does not hold then the implication above is vacuously true.
    This is the "partial correctness" criterion that is oblivious of proper termination.
    For this reason we say that P is a partial pre-condition of Q w.r.t. S
    
    About termination and the notion of total pre-condition we shall say more later.

*/

// validity of {x == 0} y := x + 3 {y < 100}
method HoareTriple1(x: int)
{
    assume x == 0;
    var y := x + 3;
    assert y < 100;
}

// validity of {x == 0} y := x + 3 {0 <= x && y == 3}
method HoareTriple2(x: int)
{
    assume x == 0;
    var y := x + 3;
    assert 0 <= x && y == 3;
}

// validity of {x == 0} y := x + 3 {true}
method HoareTriple3(x: int)
{
    assume x == 0;
    var y := x + 3;
    assert true;
}

/* Hoare logic

    Hoare logic is a system of rules to derive valid triples. In the orginal formulation
    program statements are limited to the ones that are generated by the following grammar

            S, T ::= skip | x := a | S;T | if b then S else T | while b do S

    where x is a program variable, a is an arithmetic expression, possibly including 
    program variables, b is a boolean expression such as x == 0, x != y (namely !(x == y)), 
    x > 4 && y = x * 3, 0 <= x + 2 || y > 7 etc. including the boolean constants true and false.

    Executions of program statements is understood as with ordinary imperative languages like C,
    but for the skip statement which terminates leaving the state unaffected:

           forall s : State :: (skip, s)=> s

    Since skip leaves the state unchanged, the rule for skip is just

           skip ------------
                {P} skip {P}

    for all P.

    The case of assignment x := a requires defining the meaning of a in a given state s,
    which is the evaluation of a in s. Suppos that the grammar of arithmetic expression is

        a, a' ::= x | c | a + a' ...

    where x is any variable, c represents numerical constants 0, 1, ... 
    Then we define aval a s by cases:

        aval x s = s x
        aval c s = c            (identifying the constant symbol c with its value)
        aval (a + a') s = (aval a s) + (aval a' s)
        ...

    In the third equation the + on the lefthand side of = is just a symbol, while
    the + on the righthand side is the arithmetical sum function.

    Let s[x := n] be the state defined by
    
        s[x := n] y := if y == x then n else s y

    and the predicate P[a/x] be defined by

        P[a/x] := P (s[x := aval a s])
    
    Then we can write the rule:

        assn -------------------
             {P[a/x]} x := a {P}
*/
  
//  Exercise: argue that {P[a/x]} x := a {P} is valid.

/*
    The writing P[a/x] reminds substitution in logic; for this to make sense
    observe that in Hoare logic, as well as in Dafny, predicates are defined
    by means of logical formulas. For example:

        F := y <= 43   which defines the predicate P_F s := (s y <= 43)

    where s y = aval y s and 43 = aval 43 s.

    Now F[x + 1/y] is the result of substituting each occurrence of y by x + 1, hence

        F[x + 1/y] == x + 1 <= 43

    Therefore instances of assn are

            ----------------------------------
            {x + 1 <= 43} y := x + 1 {y <= 43}
    and
            ----------------------------------
            {x + 1 <= 43} x := x + 1 {x <= 43}
*/

method HoareTriple4()
{
    var x := 100;
    assume x + 1 <= 43;
    x := x + 1;
    assert x <= 43;
}

/*  Now how to deduce {x < 43} x := x + 1 {x <= 43}? For this rule assn does not suffices; 
    indeed Hoare logic has a rule "cons" for consequentiae:

         P ==>' P'   {P'} S {Q'}   Q' ==>' Q
    cons ----------------------------------
                     {P} S {Q}

    where P ==>' P' is defined as forall s :: P s ==> P' s and
    P s ==> P' s is a valid implication of arithmetic; similarly for Q ==>' Q'.
    When P = P' (Q' = Q) namely are true of the same states, then the first (third) 
    premise can be omitted.

    Now the desired proof is

                                   assn ----------------------------------
          x < 43 ==> x + 1 <= 43        {x + 1 <= 43} x := x + 1 {x <= 43}
    cons  ----------------------------------------------------------------
                        {x < 43} x := x + 1 {x <= 43}
*/

/*  A notation for program-proofs

    Instead of using the tree form, the previous proof can be written as
    a program with predicates interspersed among the statements 
    (here we have just one):

    {x < 43}        // 1
    {x + 1 <= 43}   // 2
    x := x + 1;
    {x <= 43}       // 3

    The predicates 1 and 2 are written in consecutive lines, meaning that 1 ==> 2;
    on the other hand when there is a statement between two predicates, as it is 
    the case of 2 and 3, we mean that an instance of rule assn has been used.

*/

method swap1()
{
    var x, y := 57, 12;     // the choices of 52 and 12 are arbitrary: try others
    ghost var X, Y := x, y; // ghost variables are not part of the code

    assert x == X && y == Y;
    assert y == Y && x == X; // by (x == X && y == Y) ==> (y == Y && x == X)
    var tmp := x;
    assert y == Y && tmp == X;
    x := y;
    assert x == Y && tmp == X;
    y := tmp;
    assert x == Y && y == X;
}


/*  Composition rule

    Let S ; S' be the sequential composition of S and S', whose execution consists of
    first executing S and, if and when this phase ends, continuing executing S' from
    the state reached in the execution of S.

    The rule sequence rule is:

          {P} S {Q}     {Q} S' {R}
    comp  ------------------------
              {P} S ; S' {R}

    To argue that this rule is sound let s be such that P s and (S ; S')=> r.
    Then it must exist t such that (S, s)=> t and (S', t)=> r. 
    Then by validity of {P} S {Q} it follows that Q t; by validity of {Q} S' {R}
    it follows that R r as desired.

    This rule has been implicitly used in example swap1(). The triples

    (a) {y == Y && x == X} tmp := x {y == Y && tmp == X} 
    (b) {y == Y && tmp == X} x := y {x == Y && tmp == X}
    (c) {x == Y && tmp == X} y := tmp {x == Y && y == X}
    
    are instances of the rule (assn); then

    (d) {y == Y && x == X} tmp := x ; x := y {x == Y && tmp == X}   

    follows from (a) and (b) by (comp); finally

    (e) {y == Y && x == X} tmp := x ; x := y ; y := tmp {x == Y && y == X}

    follows from (e) and (c) again by (comp).

    The same proof, but written as a program with assertions, 
    is essentially example swap1().

*/

// Exercise: fill the missing assertions in the proof, that Dafny performs automatically

method swap2()
{
    var x, y := 57, 12;     // the choices of 52 and 12 are arbitrary
    ghost var X, Y := x, y;

    assert x == X && y == Y;
    x := y - x;
    y := y - x;
    x := x + y;
    assert x == Y && y == X;
}

/*  Conditional rule

       {P && b} S {Q}       {P && !b} T {Q}
    if -------------------------------------
           {P} if b then S else T {Q}

*/

/*  Exercise: state and derive suitable pre and post-conditions for the statement

    if x < y then m := y else m := x

    Then write a Dafny method to check your answers.
*/

method Max(x: int, y: int) returns (m: int)
    ensures m == x || m == y
    ensures x <= m && x <= m
{
    if x < y {
        m := y;
        assert m == y >= x;
    }
    else {
        assert y <= x;
        m := x;
        assert m == x >= y;
    }
}

/*  Exercise: A rule is "derivable" w.r.t. a formal system if it can be seen as abbreviating 
    a derivation with leaves labelled by the premises of the rule, and the root labelled by 
    its conclusion.

    Prove that the following rule is derivable:

    P && b ==> U   {U} S {X}    P && !b ==> V    {V} T {Y}
    ------------------------------------------------------
              {P} if b then S else T {X || Y}
*/